#ifndef _table_data_h
#define _table_data_h

/* Generated by scripts/gen-assets.py from scripts/playfield.py -- do not edit.
 *
 * The table is traced from art/pinball.png; the nine feet come from
 * art/pinball2.png.  It is diced into 39x50 cells of 4x4 pixels, covering the
 * table only -- the ball never leaves it, and a cell for the whole world would
 * cost three times as much.  A zero cell is open floor.  Any other cell packs
 * the kind of surface in the top 3 bits and the direction it faces in the low
 * 5, so one lookup tells the ball both how to bounce and what to score.
 *
 * Cell (0,0) is at world pixel (TBL_ORIGIN_X, TBL_ORIGIN_Y).
 */

#define TBL_CELL        4
#define TBL_CELL_SHIFT  2
#define TBL_GRID_W      39
#define TBL_GRID_H      50
#define TBL_ORIGIN_X    40
#define TBL_ORIGIN_Y    12
#define TBL_NUM_DIRS    32

#define TBL_KIND(c)     ((c) >> 5)
#define TBL_DIR(c)      ((c) & 31)

#define K_EMPTY   0
#define K_WALL    1
#define K_BUMPER  2
#define K_FOOT    3
#define K_SCENERY 4
#define K_DRAIN   6

/* The world is bigger than the screen so the camera has room to move; the
 * artwork is centred in it and CAMERA_X/Y is where the view sits at rest. */
#define WORLD_W          336
#define WORLD_H          224
#define CAMERA_X         8
#define CAMERA_Y         12
#define CAMERA_MAX_X     16
#define CAMERA_MAX_Y     24

/* All of these are world pixels. */
#define PLAYFIELD_LEFT   43
#define PLAYFIELD_RIGHT  194
#define LANE_X0          185
#define LANE_X1          192
#define LANE_TOP         46
#define DRAIN_Y          206
#define BALL_R           3

#define NUM_FEET         9
/* The first NUM_TOP_FEET are the ones under the pods -- the marks the manual
 * says feed Vally's tongue.  foot_boxes() returns them top row first. */
#define NUM_TOP_FEET     4
#define NUM_DIAMONDS     3
#define DIAMOND_MID_OFF  5

/* The three big bumpers, as x0, y0, x1, y1.  Striking one flashes its middle;
 * the strips and the small wall diamonds score but do not flash. */
const unsigned char tblDiamondBox[] = {
    103, 85, 118, 100, 87, 100, 102, 115, 119, 100, 134, 115,
};

/* The panel read-outs, placed from the boards drawn in the artwork. */
#define SCORE_DIGITS      7
#define SCORE_DIGIT_X0    212
#define SCORE_DIGIT_PITCH 8
#define SCORE_GROUP_GAP   2
#define HIGH_DIGIT_Y      170
#define SCORE_DIGIT_Y     192
#define MULT_DIGIT_X      280
#define MULT_DIGIT_Y      170
#define BALLS_DIGIT_X     196
#define BALLS_DIGIT_Y     198
#define BALLS_PITCH       10
#define PANEL_TONGUE_X    274
#define PANEL_TONGUE_Y    80

/* The volcano, and the two slopes the lava runs down. */
#define VOLCANO_X         228
#define VOLCANO_Y         64
/* Distances from the apex to the foot of each slope, as magnitudes: the left
 * one runs left, the right one right, and both run down.  Keeping them
 * positive keeps the shifts in 06-lava.c off negative numbers. */
#define LAVA_L_DX         15
#define LAVA_L_DY         15
#define LAVA_R_DX         11
#define LAVA_R_DY         11
#define LAVA_FRAMES       8
#define GATE_X0           177
#define GATE_Y0           25
#define GATE_X1           184
#define GATE_Y1           53

/* The nine feet, as x0, y0, x1, y1.  Hitting one turns it cyan and takes it
 * out of play until the ball drains. */
const unsigned char tblFootBox[] = {
    59, 61, 64, 64, 69, 61, 74, 64, 143, 61, 148, 64, 153, 61, 158, 64,
    100, 131, 105, 134, 108, 131, 113, 134, 116, 131, 121, 134, 153, 137, 156, 142,
    153, 145, 156, 150,
};

/* Unit normals, scaled by 32. */
const signed char tblDirX[] = {
    32, 31, 30, 27, 23, 18, 12, 6, 0, -6, -12, -18, -23, -27, -30, -31,
    -32, -31, -30, -27, -23, -18, -12, -6, 0, 6, 12, 18, 23, 27, 30, 31,
};

const signed char tblDirY[] = {
    0, 6, 12, 18, 23, 27, 30, 31, 32, 31, 30, 27, 23, 18, 12, 6,
    0, -6, -12, -18, -23, -27, -30, -31, -32, -31, -30, -27, -23, -18, -12, -6,
};

/* Flippers.  Entries 0..5 are the left flipper from rest to fully
 * raised; the next 6 are the right. */
#define FLIPPER_FRAMES   6
#define FLIPPER_LEN      19
#define FLIPPER_HALF_THICK 4
#define FLIP_L_X         86
#define FLIP_L_Y         181
#define FLIP_R_X         134
#define FLIP_R_Y         181

const signed char tblFlipDirX[] = {
    23, 29, 32, 32, 29, 23, -23, -29, -32, -32, -29, -23,
};

const signed char tblFlipDirY[] = {
    23, 15, 5, -5, -15, -23, 23, 15, 5, -5, -15, -23,
};

const signed char tblFlipNrmX[] = {
    23, 15, 5, -5, -15, -23, -23, -15, -5, 5, 15, 23,
};

const signed char tblFlipNrmY[] = {
    -23, -29, -32, -32, -29, -23, -23, -29, -32, -32, -29, -23,
};

/* The grid itself is 1950 bytes, which is a large slice of an 8K object code
 * page, so only the ball object -- the one thing that collides with the table
 * -- asks for it, by defining TBL_WANT_GRID before including this header. */
#ifdef TBL_WANT_GRID
const unsigned char tblGrid[] = {
    40, 40, 40, 36, 37, 37, 37, 38, 39, 39, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
    40, 40, 40, 40, 40, 41, 41, 41, 42, 42, 42, 43, 43, 44, 40, 40, 36, 37, 37, 37, 37, 38, 38, 39,
    39, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 41, 41, 41, 41,
    41, 41, 42, 43, 43, 43, 36, 36, 37, 37, 37, 37, 38, 38, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 41, 41, 41, 41, 42, 43, 43, 43, 36, 36, 36,
    37, 38, 38, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 42, 43, 44, 44, 35, 36, 36, 36, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 44, 45, 35, 35, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 46, 35, 34, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 152, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 47, 34, 34, 0, 0, 0, 149, 153, 0, 0, 0, 0, 0, 149, 154, 0,
    0, 148, 152, 156, 0, 0, 150, 155, 0, 0, 0, 0, 150, 153, 156, 0, 0, 0, 0, 0, 0, 0, 0, 48,
    33, 0, 0, 0, 0, 147, 152, 155, 0, 0, 0, 0, 144, 128, 0, 0, 144, 136, 128, 0, 0, 144, 128, 0,
    0, 0, 147, 149, 154, 158, 0, 0, 0, 0, 0, 0, 0, 0, 48, 33, 0, 0, 0, 0, 145, 149, 156, 158,
    0, 0, 0, 139, 134, 0, 0, 140, 136, 132, 0, 0, 138, 133, 0, 0, 0, 145, 147, 157, 159, 0, 0, 0,
    0, 55, 0, 0, 0, 48, 32, 0, 0, 0, 0, 143, 141, 129, 128, 0, 0, 0, 0, 0, 0, 0, 0, 136,
    0, 0, 0, 0, 0, 0, 0, 0, 143, 141, 132, 129, 0, 0, 0, 0, 52, 57, 0, 0, 48, 32, 0, 0,
    0, 0, 141, 138, 134, 130, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 141,
    138, 134, 130, 0, 0, 0, 0, 50, 59, 0, 0, 48, 32, 0, 0, 0, 0, 107, 0, 104, 100, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 107, 0, 104, 100, 0, 0, 0, 0, 49, 62,
    0, 0, 48, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 32, 0, 0, 48, 32, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 48, 32, 0, 0, 48, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 32, 0, 0, 48,
    63, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 49, 63, 0, 0, 48, 62, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 50, 62, 0, 0, 48, 61, 61, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 88,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 52, 62, 0, 0, 48, 60, 61, 93,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 83, 87, 92, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 83, 56, 62, 0, 0, 48, 61, 62, 62, 94, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 79, 77, 64, 95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 81, 50, 60, 63,
    0, 0, 48, 32, 32, 32, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 74, 70, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 47, 46, 36, 33, 0, 0, 48, 35, 34, 34, 66, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 87, 0, 0, 0, 0, 0, 0, 0, 90, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 45, 40, 34, 0, 0, 48, 35, 34, 67, 0, 0, 0, 0, 0, 0, 0, 0, 0, 82, 87, 94,
    0, 0, 0, 0, 0, 82, 91, 94, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 44, 34, 0, 0, 48,
    34, 66, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 78, 73, 66, 0, 0, 0, 0, 0, 77, 71, 66, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 46, 33, 0, 0, 48, 33, 65, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 73, 0, 0, 0, 0, 0, 0, 0, 71, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 49, 63, 0, 0, 48, 33, 65, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 152,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 51, 62, 0, 0, 48, 33, 65, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 149, 152, 155, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 50, 54, 62, 0, 0, 48, 33, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 145, 146, 151, 158, 158, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50, 56, 63,
    0, 0, 48, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 110, 140, 105, 133, 98, 129,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50, 59, 63, 0, 0, 48, 63, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 107, 0, 104, 0, 101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 49, 50, 62, 63, 0, 0, 48, 62, 62, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 151, 123, 0, 0, 0, 81, 49, 63, 32, 0, 0, 48,
    62, 63, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 146, 150, 126, 0, 0, 0, 80, 49, 63, 32, 0, 0, 48, 62, 62, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 142, 138, 98, 0, 0, 0, 80,
    48, 32, 32, 0, 0, 48, 62, 62, 62, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 137, 101, 0, 0, 0, 80, 49, 32, 32, 0, 0, 48, 61, 62, 62,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 80, 49, 32, 32, 0, 0, 48, 62, 62, 62, 62, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 48, 32, 32,
    0, 0, 48, 33, 33, 32, 32, 63, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 47, 47, 45, 34, 33, 0, 0, 48, 35, 34, 34, 34, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 45, 44, 36, 33, 0, 0, 48, 35, 35, 35, 0, 0, 0, 148, 88, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 89, 92, 0, 0, 0, 0, 44, 39, 34, 0, 0, 48,
    34, 34, 0, 0, 0, 0, 142, 144, 88, 91, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 84, 87, 157, 129, 0, 0, 0, 0, 0, 43, 34, 0, 0, 48, 32, 32, 0, 0, 0, 0, 0, 0, 141,
    128, 158, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 145, 144, 134, 131, 0, 0, 0, 0, 0,
    0, 47, 33, 0, 0, 48, 63, 63, 0, 0, 0, 0, 0, 0, 139, 135, 132, 130, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 141, 138, 135, 0, 0, 0, 0, 0, 0, 0, 52, 62, 0, 0, 48, 62, 62, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 55, 62, 0, 0, 48, 61, 60, 59, 59, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 54, 54, 55, 59, 62,
    0, 0, 48, 60, 60, 59, 58, 58, 57, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 54, 55, 55, 54, 54, 56, 60, 62, 0, 0, 49, 34, 33, 32, 62, 60, 59,
    58, 58, 58, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 54, 54, 54, 54, 53,
    53, 51, 48, 34, 32, 63, 0, 0, 48, 36, 37, 37, 38, 37, 34, 62, 60, 59, 59, 58, 58, 59, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 53, 54, 54, 53, 53, 52, 50, 46, 43, 41, 41, 38, 35, 33, 61, 0, 49,
    35, 37, 38, 39, 40, 39, 39, 38, 36, 33, 61, 60, 60, 59, 59, 0, 0, 0, 0, 0, 53, 53, 52, 52,
    51, 47, 44, 42, 41, 41, 40, 40, 40, 39, 37, 36, 36, 49, 48, 32, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
};
#endif

#endif /* _table_data_h */
